/* Tarih ve Firma numaralarını aktif döneme göre değiştiriniz*/
SELECT 
  EMU.CODE [HESAP KODU], 
  EMU.DEFINITION_ [HESAP ADI], 
  SUM(EMF.DEBIT) AS BORC, 
  SUM(EMF.CREDIT) AS ALACAK, 
  (
    SUM(EMF.DEBIT)- SUM(EMF.CREDIT)
  ) AS BAKIYE 
FROM 
  LG_XX_EMUHACC EMU 
  INNER JOIN LG_XXX_XX_EMFLINE EMF ON EMU.LOGICALREF = EMF.ACCOUNTREF 
WHERE 
  EMF.DATE_ BETWEEN '20200101' AND '20201231' 
GROUP BY 
  EMU.CODE, 
  EMU.DEFINITION_
