
/* Tarih ve Firma numaralarýný aktif döneme göre deðiþitiriniz*/
SELECT EMU.CODE [HESAP KODU],EMU.DEFINITION_ [HESAP ADI],SUM(EMF.DEBIT) AS BORC, SUM(EMF.CREDIT) AS ALACAK,(SUM(EMF.DEBIT)-SUM(EMF.CREDIT)) AS BAKIYE
FROM LG_060_EMUHACC EMU
INNER JOIN LG_060_01_EMFLINE EMF ON EMU.LOGICALREF=EMF.ACCOUNTREF
--WHERE EMF.DATE_ BETWEEN '20200101' AND '20201231' 

GROUP BY EMU.CODE,EMU.DEFINITION_


