SELECT
INVOICE.DATE_ AS FATURA_TARIHI,
INVOICE.FICHENO FATURA_NO,
SLSMAN.DEFINITION_ AS SATIS_TEMSILCISI,
CLCARD.CODE AS CARI_KOD,
CLCARD.DEFINITION_ AS CARI,

CASE WHEN STLINE.LINETYPE=4 THEN SRV.CODE ELSE ITEMS.CODE END AS [Malzeme Kod],
CASE WHEN STLINE.LINETYPE=4 THEN SRV.DEFINITION_ ELSE ITEMS.NAME END AS [Malzeme Ad],


ITEMS.CODE AS URUN_KODU,
ITEMS.NAME AS URUN_ADI,
STLINE.AMOUNT AS MIKTARI,
MAINUNITSETL.CODE AS BIRIM,
STLINE.PRICE / UNITSETL.CONVFACT1 * UNITSETL.CONVFACT2 AS SATIS_BIRIM_FIYATI,

STLINE.DISTDISC AS INDIRIM,
STLINE.VAT [KDV %],
STLINE.VATMATRAH [KDV Matrah],

STLINE.VATAMNT AS KDV_TUTAR,
STLINE.TOTAL AS TOPLAM_TUTAR,
STLINE.LINENET / UNITSETL.CONVFACT1 * UNITSETL.CONVFACT2 AS SATIS_NET_TUTARI,



(CASE 
WHEN INVOICE.TRCODE=1  	THEN 'Sat�nalma Faturas�'
WHEN INVOICE.TRCODE=2  	THEN 'Perakende Sat�� �ade Faturas�'
WHEN INVOICE.TRCODE=3  	THEN 'Toptan Sat�� �ade Faturas�'
WHEN INVOICE.TRCODE=4  	THEN 'Al�nan Hizmet Faturas�'
WHEN INVOICE.TRCODE=5  	THEN 'Al�nan Proforma Faturas�'
WHEN INVOICE.TRCODE=6  	THEN 'Sat�nalma �ade Faturas�'
WHEN INVOICE.TRCODE=7  	THEN 'Perakende Sat�� Faturas�'
WHEN INVOICE.TRCODE=8  	THEN 'Toptan Sat�� Faturas�'
WHEN INVOICE.TRCODE=9  	THEN 'Verilen Hizmet Faturas�'
WHEN INVOICE.TRCODE=10  THEN 'Verilen Proforma Faturas�'
WHEN INVOICE.TRCODE=12  THEN 'Al�nan Vade Fark� Faturas�'
WHEN INVOICE.TRCODE=13  THEN 'Sat�nalma Fiyat Fark� Faturas�'
WHEN INVOICE.TRCODE=14  THEN 'Sat�� Fiyat Fark� Faturas�'
WHEN INVOICE.TRCODE=26  THEN 'M�stahsil Makbuzu' END
) as [Fatura Tipi],

CASE 
WHEN CLCARD.ISPERSCOMP=1 THEN CLCARD.TCKNO 
ELSE CLCARD.TAXNR END AS [VKN/TCKN],

CASE 
WHEN CLCARD.ISPERSCOMP=1 THEN 'TC'
ELSE 
CLCARD.TAXOFFICE END AS [VERGI_DAIRESI],

EMUH.DEFINITION_ as [Muhasebe Hesap Plan� Ad],

INVOICE.GENEXP1 +INVOICE.GENEXP2 [A��klama]

    FROM LG_060_01_INVOICE INVOICE
									
	                                LEFT JOIN LG_060_CLCARD CLCARD ON CLCARD.LOGICALREF = INVOICE.CLIENTREF
	                                LEFT JOIN LG_060_01_STLINE STLINE ON STLINE.INVOICEREF = INVOICE.LOGICALREF
	                                LEFT JOIN LG_060_ITEMS ITEMS ON ITEMS.LOGICALREF = STLINE.STOCKREF
									RIGHT JOIN LG_060_UNITSETL MAINUNITSETL ON MAINUNITSETL.UNITSETREF = STLINE.USREF AND MAINUNITSETL.MAINUNIT = 1
	                                LEFT JOIN LG_060_UNITSETL UNITSETL ON UNITSETL.LOGICALREF = STLINE.UOMREF
									LEFT JOIN LG_SLSMAN SLSMAN ON INVOICE.SALESMANREF = SLSMAN.LOGICALREF
									LEFT JOIN LG_060_EMUHACC EMUH ON EMUH.LOGICALREF=STLINE.ACCOUNTREF
									LEFT JOIN LG_060_SRVCARD SRV ON SRV.LOGICALREF=STLINE.STOCKREF
WHERE(INVOICE.TRCODE IN(2,3,7,8,9,10,14))

ORDER BY INVOICE.DATE_,
INVOICE.FICHENO
